"""empty message

Revision ID: 837e0a905a55
Revises: f1c60768841c
Create Date: 2016-02-08 12:22:41.156574

"""

# revision identifiers, used by Alembic.
revision = '837e0a905a55'
down_revision = 'f1c60768841c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musicas', sa.Column('cifra_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('musicas', 'cifra_url')
    ### end Alembic commands ###
