"""empty message

Revision ID: b2b2731b2d17
Revises: None
Create Date: 2016-01-31 00:51:55.578480

"""

# revision identifiers, used by Alembic.
revision = 'b2b2731b2d17'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cantor', sa.String(), nullable=True),
    sa.Column('sequencia', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estrofes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musica_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['musica_id'], ['musicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estrofe_id', sa.Integer(), nullable=True),
    sa.Column('cifra', sa.String(), nullable=True),
    sa.Column('letra', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['estrofe_id'], ['estrofes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('versos')
    op.drop_table('estrofes')
    op.drop_table('musicas')
    ### end Alembic commands ###
