"""empty message

Revision ID: f1c60768841c
Revises: 418d10e96519
Create Date: 2016-02-01 01:01:36.062277

"""

# revision identifiers, used by Alembic.
revision = 'f1c60768841c'
down_revision = '418d10e96519'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cantores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'musicas', sa.Column('cantor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'musicas', 'cantores', ['cantor_id'], ['id'])
    op.drop_column(u'musicas', 'cantor')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'musicas', sa.Column('cantor', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'musicas', type_='foreignkey')
    op.drop_column(u'musicas', 'cantor_id')
    op.drop_table('cantores')
    ### end Alembic commands ###
